[config]
model = "gpt-4o"
model_turbo = "gpt-4o"
fallback_models = ["gpt-4o"]
response_language = "zh-CN"

[pr_reviewer]  
extra_instructions = "请用中文回复，并且要详细分析代码质量"  
  
[pr_description]  
extra_instructions = "请用中文生成PR描述，包含详细的变更说明"